
export const mockAuditData = [
  {
    id: '1',
    claimNumber: '12345',
    claimDate: '10-02-2025',
    hospitalName: 'ABC Hospital',
    hospitalLocation: 'Location A',
    htpaLocation: 'Region 1',
    dateOfAdmission: '28-01-2025',
    dateOfDischarge: '31-01-2025',
    fraudTriggers: 'Data Anomaly',
    fieldInvestigationDate: '28-02-2025',
    claimStatus: 'Pending',
    status: 'Desk Audit',
    deskAuditReferralDate: '01-03-2025',
    taTCompliance: '+3 Days',
    claimIntimationAging: '+2 Days',
    aiManualTrigger: 'AI',
    allocation: 'RO Admin 1',
    fieldReport: 'Download Report'
  },
  {
    id: '2',
    claimNumber: '12346',
    claimDate: '10-02-2025',
    hospitalName: 'Vincent Hospital',
    hospitalLocation: 'Andhra Pradesh',
    htpaLocation: 'Hyderabad',
    dateOfAdmission: '28-01-2025',
    dateOfDischarge: '31-01-2025',
    fraudTriggers: 'Duplicate Claim',
    fieldInvestigationDate: '28-02-2025',
    claimStatus: 'Processed',
    status: 'Claim Processing',
    deskAuditReferralDate: '01-03-2025',
    taTCompliance: '+3 Days',
    claimIntimationAging: '-2 Days',
    aiManualTrigger: 'Manual',
    allocation: 'RO Admin 3',
    fieldReport: 'Download Report'
  },
  {
    id: '3',
    claimNumber: '12347',
    claimDate: '10-02-2025',
    hospitalName: 'Vincent Hospital',
    hospitalLocation: 'Andhra Pradesh',
    htpaLocation: 'Hyderabad',
    dateOfAdmission: '28-01-2025',
    dateOfDischarge: '31-01-2025',
    fraudTriggers: 'Duplicate Claim',
    fieldInvestigationDate: '28-02-2025',
    claimStatus: 'Processed',
    status: 'Claim Processing',
    deskAuditReferralDate: '01-03-2025',
    taTCompliance: '+3 Days',
    claimIntimationAging: '-2 Days',
    aiManualTrigger: 'Manual',
    allocation: 'RO Admin 3',
    fieldReport: 'Download Report'
  },
  {
    id: '4',
    claimNumber: '12348',
    claimDate: '10-02-2025',
    hospitalName: 'Vincent Hospital',
    hospitalLocation: 'Andhra Pradesh',
    htpaLocation: 'Hyderabad',
    dateOfAdmission: '28-01-2025',
    dateOfDischarge: '31-01-2025',
    fraudTriggers: 'Duplicate Claim',
    fieldInvestigationDate: '28-02-2025',
    claimStatus: 'Processed',
    status: 'Claim Processing',
    deskAuditReferralDate: '01-03-2025',
    taTCompliance: '+3 Days',
    claimIntimationAging: '-2 Days',
    aiManualTrigger: 'Manual',
    allocation: 'RO Admin 3',
    fieldReport: 'Download Report'
  },
  {
    id: '5',
    claimNumber: '12349',
    claimDate: '10-02-2025',
    hospitalName: 'Vincent Hospital',
    hospitalLocation: 'Andhra Pradesh',
    htpaLocation: 'Hyderabad',
    dateOfAdmission: '28-01-2025',
    dateOfDischarge: '31-01-2025',
    fraudTriggers: 'Duplicate Claim',
    fieldInvestigationDate: '28-02-2025',
    claimStatus: 'Processed',
    status: 'Claim Processing',
    deskAuditReferralDate: '01-03-2025',
    taTCompliance: '+3 Days',
    claimIntimationAging: '-2 Days',
    aiManualTrigger: 'Manual',
    allocation: 'RO Admin 3',
    fieldReport: 'Download Report'
  },
  {
    id: '6',
    claimNumber: '12350',
    claimDate: '11-02-2025',
    hospitalName: 'Metro Hospital',
    hospitalLocation: 'Karnataka',
    htpaLocation: 'Bangalore',
    dateOfAdmission: '29-01-2025',
    dateOfDischarge: '02-02-2025',
    fraudTriggers: 'Policy Violation',
    fieldInvestigationDate: '01-03-2025',
    claimStatus: 'Under Review',
    status: 'Investigation',
    deskAuditReferralDate: '02-03-2025',
    taTCompliance: '+2 Days',
    claimIntimationAging: '+1 Days',
    aiManualTrigger: 'AI',
    allocation: 'Desk Auditor 1',
    fieldReport: 'Download Report'
  },
  {
    id: '7',
    claimNumber: '12351',
    claimDate: '12-02-2025',
    hospitalName: 'City Hospital',
    hospitalLocation: 'Tamil Nadu',
    htpaLocation: 'Chennai',
    dateOfAdmission: '30-01-2025',
    dateOfDischarge: '03-02-2025',
    fraudTriggers: 'Billing Discrepancy',
    fieldInvestigationDate: '02-03-2025',
    claimStatus: 'Pending',
    status: 'Desk Audit',
    deskAuditReferralDate: '03-03-2025',
    taTCompliance: '+1 Days',
    claimIntimationAging: '+3 Days',
    aiManualTrigger: 'Manual',
    allocation: 'RO Admin 2',
    fieldReport: 'Download Report'
  }
];
